services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "123123mm"
      ACCEPT_EULA: "Y"
  hrm.apis:
    container_name: hrm_api
    image: ${DOCKER_REGISTRY-}hrmapis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7025:7025"
      - "7021:7021"    
    environment:
      DB_HOST: "sql_server_container"
      DB_NAME: "HRM"
      DB_USER: "sa"
      DB_PASSWORD: "Trinhkhanh1@#3212@@Tqom"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - sql_server